package Entregable1920.Pizzeria2;

public enum Favoritas {
    JAMON_SERRANO_QUESO_MEDIANA, JAMON_SERRANO_QUESO_FAMILIAR, BARBACOA_MEDIANA,
    BARBACOA_FAMILIAR, CARBONARA_MEDIANA, CARBONARA_FAMILIAR, MARGARITA_MEDIANA
}
